{ pkgs, ... }:

  with pkgs; [
   git
   kitty
   starship
   discord
   pavucontrol
   clang
   zig
   vlc
   alsa-utils
   alsa-ucm-conf
   fastfetch
   ghostty
   xfce.thunar
   xfce.tumbler
   xfce.thunar-volman
   # nautilus
   gnome-tweaks
   gnome-extension-manager
   google-chrome
   carapace
   zoxide
   btop
   obs-studio
   # python2
   #cope
   #python311Packages.pip
   #python312Packages.pip
   #python313Packages.pip
   # spotify
   hyprpaper
   hyprpolkitagent
   rofi-wayland
   blueman
   waybar
   adw-gtk3
   whitesur-gtk-theme
   qt5.qtwayland
   qt6.qtwayland
   libsForQt5.qt5ct
   qt6ct
   hyprshot
   hyprpicker
   gtk3
   gtk4
   gtk-layer-shell
   go
   wlogout
   hyprlock
   hypridle
   wayland-utils
   wayland-protocols
   waypaper
   swaynotificationcenter
   noto-fonts
	 noto-fonts-color-emoji
   nerd-fonts.fira-code
   nerd-fonts.jetbrains-mono
   cliphist
   wlr-randr
   wl-clipboard
   #dunst
   rofimoji
   rofi-emoji-wayland
   kdePackages.gwenview
   kdePackages.kdeconnect-kde
   hyprshot
   swappy
   grim
   slurp
   playerctl
   spicetify-cli
   fuzzel
   wev
   cava
   brightnessctl
   pamixer
   gimp3
   upower
   polkit_gnome
   gnome-keyring
   libcanberra-gtk3
   libreoffice
   corefonts
   cmatrix
   cbonsai
   neofetch
   nwg-dock-hyprland
   vscode
   zoom-us
   net-tools
   swww
   putty
   anyrun
   filebrowser
   nchat
   nodejs
   winbox4
   caffeine
   ciscoPacketTracer8
   bibata-cursors
   xdg-desktop-portal
   xdg-desktop-portal-gtk
   xdg-desktop-portal-hyprland
  ]
